// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MasterNodeProtocol.proto

package com.clusterwork.protocol;

public final class MasterNodeProtocolProtos {
  private MasterNodeProtocolProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IssuedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];
    /**
     * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
     */
    boolean hasTerminal();
    /**
     * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
     */
    com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType getTerminal();

    // required int64 Identity = 3;
    /**
     * <code>required int64 Identity = 3;</code>
     */
    boolean hasIdentity();
    /**
     * <code>required int64 Identity = 3;</code>
     */
    long getIdentity();

    // required int32 command = 4;
    /**
     * <code>required int32 command = 4;</code>
     */
    boolean hasCommand();
    /**
     * <code>required int32 command = 4;</code>
     */
    int getCommand();

    // optional bytes args = 5;
    /**
     * <code>optional bytes args = 5;</code>
     */
    boolean hasArgs();
    /**
     * <code>optional bytes args = 5;</code>
     */
    com.google.protobuf.ByteString getArgs();
  }
  /**
   * Protobuf type {@code com.clusterwork.proto.Issued}
   */
  public static final class Issued extends
      com.google.protobuf.GeneratedMessage
      implements IssuedOrBuilder {
    // Use Issued.newBuilder() to construct.
    private Issued(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Issued(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Issued defaultInstance;
    public static Issued getDefaultInstance() {
      return defaultInstance;
    }

    public Issued getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Issued(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType value = com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                terminal_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              identity_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              command_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              args_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Issued_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Issued_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.class, com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.Builder.class);
    }

    public static com.google.protobuf.Parser<Issued> PARSER =
        new com.google.protobuf.AbstractParser<Issued>() {
      public Issued parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Issued(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Issued> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.clusterwork.proto.Issued.TerminalType}
     */
    public enum TerminalType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER = 0;</code>
       */
      SERVER(0, 0),
      /**
       * <code>NODE = 1;</code>
       */
      NODE(1, 1),
      /**
       * <code>ADMIN = 2;</code>
       */
      ADMIN(2, 2),
      ;

      /**
       * <code>SERVER = 0;</code>
       */
      public static final int SERVER_VALUE = 0;
      /**
       * <code>NODE = 1;</code>
       */
      public static final int NODE_VALUE = 1;
      /**
       * <code>ADMIN = 2;</code>
       */
      public static final int ADMIN_VALUE = 2;


      public final int getNumber() { return value; }

      public static TerminalType valueOf(int value) {
        switch (value) {
          case 0: return SERVER;
          case 1: return NODE;
          case 2: return ADMIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TerminalType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<TerminalType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TerminalType>() {
              public TerminalType findValueByNumber(int number) {
                return TerminalType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.getDescriptor().getEnumTypes().get(0);
      }

      private static final TerminalType[] VALUES = values();

      public static TerminalType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private TerminalType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.clusterwork.proto.Issued.TerminalType)
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];
    public static final int TERMINAL_FIELD_NUMBER = 2;
    private com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType terminal_;
    /**
     * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
     */
    public boolean hasTerminal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
     */
    public com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType getTerminal() {
      return terminal_;
    }

    // required int64 Identity = 3;
    public static final int IDENTITY_FIELD_NUMBER = 3;
    private long identity_;
    /**
     * <code>required int64 Identity = 3;</code>
     */
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 Identity = 3;</code>
     */
    public long getIdentity() {
      return identity_;
    }

    // required int32 command = 4;
    public static final int COMMAND_FIELD_NUMBER = 4;
    private int command_;
    /**
     * <code>required int32 command = 4;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 command = 4;</code>
     */
    public int getCommand() {
      return command_;
    }

    // optional bytes args = 5;
    public static final int ARGS_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString args_;
    /**
     * <code>optional bytes args = 5;</code>
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes args = 5;</code>
     */
    public com.google.protobuf.ByteString getArgs() {
      return args_;
    }

    private void initFields() {
      version_ = 0;
      terminal_ = com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType.NODE;
      identity_ = 0L;
      command_ = 0;
      args_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTerminal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdentity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, terminal_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, identity_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, command_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, args_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, terminal_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, identity_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, command_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, args_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.clusterwork.protocol.MasterNodeProtocolProtos.Issued prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.clusterwork.proto.Issued}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.clusterwork.protocol.MasterNodeProtocolProtos.IssuedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Issued_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Issued_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.class, com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.Builder.class);
      }

      // Construct using com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        terminal_ = com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType.NODE;
        bitField0_ = (bitField0_ & ~0x00000002);
        identity_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        args_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Issued_descriptor;
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Issued getDefaultInstanceForType() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.getDefaultInstance();
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Issued build() {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Issued result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Issued buildPartial() {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Issued result = new com.clusterwork.protocol.MasterNodeProtocolProtos.Issued(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.terminal_ = terminal_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.identity_ = identity_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.args_ = args_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.clusterwork.protocol.MasterNodeProtocolProtos.Issued) {
          return mergeFrom((com.clusterwork.protocol.MasterNodeProtocolProtos.Issued)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.clusterwork.protocol.MasterNodeProtocolProtos.Issued other) {
        if (other == com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTerminal()) {
          setTerminal(other.getTerminal());
        }
        if (other.hasIdentity()) {
          setIdentity(other.getIdentity());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasArgs()) {
          setArgs(other.getArgs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTerminal()) {
          
          return false;
        }
        if (!hasIdentity()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Issued parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.clusterwork.protocol.MasterNodeProtocolProtos.Issued) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];
      private com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType terminal_ = com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType.NODE;
      /**
       * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
       */
      public boolean hasTerminal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
       */
      public com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType getTerminal() {
        return terminal_;
      }
      /**
       * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
       */
      public Builder setTerminal(com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        terminal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.clusterwork.proto.Issued.TerminalType terminal = 2 [default = NODE];</code>
       */
      public Builder clearTerminal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        terminal_ = com.clusterwork.protocol.MasterNodeProtocolProtos.Issued.TerminalType.NODE;
        onChanged();
        return this;
      }

      // required int64 Identity = 3;
      private long identity_ ;
      /**
       * <code>required int64 Identity = 3;</code>
       */
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 Identity = 3;</code>
       */
      public long getIdentity() {
        return identity_;
      }
      /**
       * <code>required int64 Identity = 3;</code>
       */
      public Builder setIdentity(long value) {
        bitField0_ |= 0x00000004;
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Identity = 3;</code>
       */
      public Builder clearIdentity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        identity_ = 0L;
        onChanged();
        return this;
      }

      // required int32 command = 4;
      private int command_ ;
      /**
       * <code>required int32 command = 4;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 command = 4;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <code>required int32 command = 4;</code>
       */
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000008;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 command = 4;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000008);
        command_ = 0;
        onChanged();
        return this;
      }

      // optional bytes args = 5;
      private com.google.protobuf.ByteString args_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes args = 5;</code>
       */
      public boolean hasArgs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes args = 5;</code>
       */
      public com.google.protobuf.ByteString getArgs() {
        return args_;
      }
      /**
       * <code>optional bytes args = 5;</code>
       */
      public Builder setArgs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes args = 5;</code>
       */
      public Builder clearArgs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.clusterwork.proto.Issued)
    }

    static {
      defaultInstance = new Issued(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.clusterwork.proto.Issued)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 Identity = 1;
    /**
     * <code>required int64 Identity = 1;</code>
     */
    boolean hasIdentity();
    /**
     * <code>required int64 Identity = 1;</code>
     */
    long getIdentity();

    // required bool Complete = 2;
    /**
     * <code>required bool Complete = 2;</code>
     */
    boolean hasComplete();
    /**
     * <code>required bool Complete = 2;</code>
     */
    boolean getComplete();

    // optional string msg = 3;
    /**
     * <code>optional string msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    // optional bytes args = 4;
    /**
     * <code>optional bytes args = 4;</code>
     */
    boolean hasArgs();
    /**
     * <code>optional bytes args = 4;</code>
     */
    com.google.protobuf.ByteString getArgs();
  }
  /**
   * Protobuf type {@code com.clusterwork.proto.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              identity_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              complete_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              args_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clusterwork.protocol.MasterNodeProtocolProtos.Response.class, com.clusterwork.protocol.MasterNodeProtocolProtos.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 Identity = 1;
    public static final int IDENTITY_FIELD_NUMBER = 1;
    private long identity_;
    /**
     * <code>required int64 Identity = 1;</code>
     */
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 Identity = 1;</code>
     */
    public long getIdentity() {
      return identity_;
    }

    // required bool Complete = 2;
    public static final int COMPLETE_FIELD_NUMBER = 2;
    private boolean complete_;
    /**
     * <code>required bool Complete = 2;</code>
     */
    public boolean hasComplete() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool Complete = 2;</code>
     */
    public boolean getComplete() {
      return complete_;
    }

    // optional string msg = 3;
    public static final int MSG_FIELD_NUMBER = 3;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes args = 4;
    public static final int ARGS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString args_;
    /**
     * <code>optional bytes args = 4;</code>
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes args = 4;</code>
     */
    public com.google.protobuf.ByteString getArgs() {
      return args_;
    }

    private void initFields() {
      identity_ = 0L;
      complete_ = false;
      msg_ = "";
      args_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdentity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComplete()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, identity_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, complete_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, args_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, identity_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, complete_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, args_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.clusterwork.protocol.MasterNodeProtocolProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.clusterwork.protocol.MasterNodeProtocolProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.clusterwork.proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.clusterwork.protocol.MasterNodeProtocolProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.clusterwork.protocol.MasterNodeProtocolProtos.Response.class, com.clusterwork.protocol.MasterNodeProtocolProtos.Response.Builder.class);
      }

      // Construct using com.clusterwork.protocol.MasterNodeProtocolProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        identity_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        complete_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        args_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.internal_static_com_clusterwork_proto_Response_descriptor;
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Response getDefaultInstanceForType() {
        return com.clusterwork.protocol.MasterNodeProtocolProtos.Response.getDefaultInstance();
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Response build() {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.clusterwork.protocol.MasterNodeProtocolProtos.Response buildPartial() {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Response result = new com.clusterwork.protocol.MasterNodeProtocolProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identity_ = identity_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.complete_ = complete_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.args_ = args_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.clusterwork.protocol.MasterNodeProtocolProtos.Response) {
          return mergeFrom((com.clusterwork.protocol.MasterNodeProtocolProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.clusterwork.protocol.MasterNodeProtocolProtos.Response other) {
        if (other == com.clusterwork.protocol.MasterNodeProtocolProtos.Response.getDefaultInstance()) return this;
        if (other.hasIdentity()) {
          setIdentity(other.getIdentity());
        }
        if (other.hasComplete()) {
          setComplete(other.getComplete());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasArgs()) {
          setArgs(other.getArgs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdentity()) {
          
          return false;
        }
        if (!hasComplete()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.clusterwork.protocol.MasterNodeProtocolProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.clusterwork.protocol.MasterNodeProtocolProtos.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 Identity = 1;
      private long identity_ ;
      /**
       * <code>required int64 Identity = 1;</code>
       */
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 Identity = 1;</code>
       */
      public long getIdentity() {
        return identity_;
      }
      /**
       * <code>required int64 Identity = 1;</code>
       */
      public Builder setIdentity(long value) {
        bitField0_ |= 0x00000001;
        identity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Identity = 1;</code>
       */
      public Builder clearIdentity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identity_ = 0L;
        onChanged();
        return this;
      }

      // required bool Complete = 2;
      private boolean complete_ ;
      /**
       * <code>required bool Complete = 2;</code>
       */
      public boolean hasComplete() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool Complete = 2;</code>
       */
      public boolean getComplete() {
        return complete_;
      }
      /**
       * <code>required bool Complete = 2;</code>
       */
      public Builder setComplete(boolean value) {
        bitField0_ |= 0x00000002;
        complete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool Complete = 2;</code>
       */
      public Builder clearComplete() {
        bitField0_ = (bitField0_ & ~0x00000002);
        complete_ = false;
        onChanged();
        return this;
      }

      // optional string msg = 3;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // optional bytes args = 4;
      private com.google.protobuf.ByteString args_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes args = 4;</code>
       */
      public boolean hasArgs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes args = 4;</code>
       */
      public com.google.protobuf.ByteString getArgs() {
        return args_;
      }
      /**
       * <code>optional bytes args = 4;</code>
       */
      public Builder setArgs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes args = 4;</code>
       */
      public Builder clearArgs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.clusterwork.proto.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.clusterwork.proto.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_clusterwork_proto_Issued_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_clusterwork_proto_Issued_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_clusterwork_proto_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_clusterwork_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MasterNodeProtocol.proto\022\025com.clusterw" +
      "ork.proto\"\277\001\n\006Issued\022\017\n\007version\030\001 \002(\005\022B\n" +
      "\010terminal\030\002 \002(\0162*.com.clusterwork.proto." +
      "Issued.TerminalType:\004NODE\022\020\n\010Identity\030\003 " +
      "\002(\003\022\017\n\007command\030\004 \002(\005\022\014\n\004args\030\005 \001(\014\"/\n\014Te" +
      "rminalType\022\n\n\006SERVER\020\000\022\010\n\004NODE\020\001\022\t\n\005ADMI" +
      "N\020\002\"I\n\010Response\022\020\n\010Identity\030\001 \002(\003\022\020\n\010Com" +
      "plete\030\002 \002(\010\022\013\n\003msg\030\003 \001(\t\022\014\n\004args\030\004 \001(\014B4" +
      "\n\030com.clusterwork.protocolB\030MasterNodePr" +
      "otocolProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_clusterwork_proto_Issued_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_clusterwork_proto_Issued_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_clusterwork_proto_Issued_descriptor,
              new java.lang.String[] { "Version", "Terminal", "Identity", "Command", "Args", });
          internal_static_com_clusterwork_proto_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_clusterwork_proto_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_clusterwork_proto_Response_descriptor,
              new java.lang.String[] { "Identity", "Complete", "Msg", "Args", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
